# Source: https://github.com/confluentinc/cp-all-in-one/blob/7.2.1-post/cp-all-in-one-community/docker-compose.yml

version: "3.9"

services:
  producer:
    build:
      context: .
      dockerfile: docker/producer/Dockerfile
    hostname: producer
    container_name: producer
    depends_on:
      - broker
      - schema-registry
    volumes:
      - ./demo/producer:/app
      - ./demo/proto/build:/app/proto
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - kafka-protobuf-demo

  consumer:
    build:
      context: .
      dockerfile: docker/consumer/Dockerfile
    hostname: consumer
    container_name: consumer
    depends_on:
      - broker
      - schema-registry
    volumes:
      - ./demo/consumer:/app
      - ./demo/proto/build:/app/proto
    env_file:
      - ./.env
    networks:
      - kafka-protobuf-demo

networks:
  kafka-protobuf-demo: